### PR TITLE
Update default.yml to support Ruby 3.x

### PR DESCRIPTION
**Pull request by jedschneider**
### What ticket(s) or other PRs does this relate to?

https://github.com/highwingio/lambdas/pull/3942

### What was the solution?

- [x] Security Impact has been considered (if yes please describe)
- [x] Network Impacts have been considered (if yes please describe)

### CODE REVIEW

**Comment by jedschneider** [comment]
do we need to tag a release to bump usage across projects?

**Review by plukevdh — APPROVED** [review]
We'll need to bump this in at least lambdas via `bundle update livery`

**Comment by jayzes** [comment]
@jedschneider probably not a bad idea. is there anything we could add here in terms of checks that would validate the base config?

**Comment by jayzes** [comment]
Also, there _should_ be a way to get Dependabot to help keep these in sync downstream. Not sure exactly how it works though.

**Review by jayzes — APPROVED** [review]

**Comment by jedschneider** [comment]
> Also, there _should_ be a way to get Dependabot to help keep these in sync downstream. Not sure exactly how it works though.

a quick search says that we will need to give dependabot access to the repos in our org, but I assume it already does?
https://github.blog/2021-03-15-dependabot-private-dependencies/

**Pull request merged**
